---
# - name: install packages in failure tasks
#   apt:
#     name: "{{item}}"
#     state: present
#   with_items: "{{apt_packages}}"


- name: On failure Task
  ansible.builtin.debug:
    msg: "On failure Task"