---
# - name: install packages in failure tasks
#   apt:
#     name: "{{item}}"
#     state: present
#   with_items: "{{apt_packages}}"
- name: Before Task
  ansible.builtin.debug:
    msg: "Before Task"
